### PR TITLE
[q-mr1] Fix front cam

### PR DESCRIPTION
**Pull request by sjllls**
_**Reason**_
For some legacy apps, camera ID 1 is front camera, that's why we can't open front camera in AOSP camera app. For Gcam and Open Camera, they recognize front cam according to [this flag](https://github.com/sonyxperiadev/device-sony-pdx201/blob/master/rootdir/vendor/etc/camera/camera_config.xml#L35) in camera configs. We need to set our front cam to ID 1, this is the right solution. For software compatibility, we must fix this problem.

**_Method_**
I checked the camera hal and stock firmwares.
1. In [camera hal,](https://github.com/sonyxperiadev/camera/blob/aosp/LA.UM.8.11.r1/QCamera2/stack/mm-camera-interface/src/mm_camera_interface.c#L2481..L2493) it tells us directly, we need to set the uwide and tele cams as AUX cam, then expose them with `persist.vendor.camera.expose.aux=1`

```
    memset(prop, 0, sizeof(prop));
    property_get("persist.vendor.camera.expose.aux", prop, "0");
    expose_aux = atoi(prop);
```
```

    /* Order of the camera exposed is
        0  - Back Main Camera
        1  - Front Main Camera
        ++  - Back Aux Camera
        ++  - Front Aux Camera
        ++  - Back Main + Back Aux camera
        ++  - Front Main + Front Aux camera
        ++  - Secure Camera
       */
```
2. In kirin's [stock firmware](https://dumps.tadiphone.dev/dumps/sony/kirin/-/blob/kirin-user-9-P-GANGES-CAF-190726-0522-1-dev-keys/system/system/build.prop#L317), they did as my guess.
Also [Motorola G Stylus](https://dumps.tadiphone.dev/dumps/motorola/sofiar/-/blob/sofiar_retail-user-11-RPES31.Q4U-47-35-5-50a0a-release-keys/vendor/build.prop#L83) , it uses sm6125 too.
```
#Expose aux camera
vendor.camera.aux.packagelist=org.codeaurora.snapcam,com.sonyericsson.android.camera,com.sonyericsson.android.servicemenu
persist.vendor.camera.expose.aux=1
```
3. What's the `StereoConfig` in camera config?
This should be a private function of seine stock camera hal, they use their own way to expose AUX cams without props. All in all, we need to set AUX cam and expose them.

4. Current cam IDs
```
Main back camera   0
Telescope camera   1
Ultra-wide camera  2
Front camera       3
```
After fixing, the right cam IDs should be
```
Main back camera   0
Front camera       1
Telescope camera   2
Ultra-wide camera  3
```

_**To be done**_
<del>1. Exposing AUX cameras needs `HAL1` support, we are lacking it.</del>
`08-26 23:38:25.976   837   837 I QCamera : <MCI><INFO> needHAL1Support: 332: ONLY HAL3 SUPPORTED`
2. Enable HAL1 support will break camera hal.

### CODE REVIEW

**Comment by bartcubbins** [comment]
I would split this commit [pdx201: camera: Set AUX camera](https://github.com/sonyxperiadev/device-sony-pdx201/pull/31/commits/362280abb9929ac0ed2c7b5278c43b043cca7074) into two, since in it we made several changes, changed the camera modules sorting and fixed the position of the rear AUX cameras

**Comment by MarijnS95** [comment]
Having certain bits of your PR description in the individual commits would be nice! Such as `Order of the camera exposed is`, having that detail in 77f0df7f3c9c97a3cbe6219ccc2c9003d98e5776 makes it easier to read the commit log without github.

**Comment by sjllls** [comment]
> Having certain bits of your PR description in the individual commits would be nice! Such as `Order of the camera exposed is`, having that detail in [77f0df7](https://github.com/sonyxperiadev/device-sony-pdx201/commit/77f0df7f3c9c97a3cbe6219ccc2c9003d98e5776) makes it easier to read the commit log without github.

Thanks, pushed! ;D

**Comment by MarijnS95** [comment]
> Thanks, pushed! ;D

Perfect, thanks a lot!

(PS. for next time, feel free to strip off irrelevant info like the timestamp and PID, to make the lines a bit shorter)

**Review by MarijnS95 — APPROVED** [review]

**Pull request merged**
