### PR TITLE
[SEINE] [URGENT] Fix wide- and zoom camera

### PR DESCRIPTION
**Pull request by MarijnS95**
This commit wasn't actually removing duplicate nodes, camera 1 and 3 are listed in `<SensorNode>` within the `<SensorConfig>` block, which is _different_ from `CameraModuleConfig` that was removed.

Reverting the commit gives us back the zoom and wideangle camera again.

@jerpelea can you check if `StereoConfig` is what you intended to remove?

### CODE REVIEW

**Comment by pablomh** [comment]
As talk privately, this PR seems to break AOSP camera which "force-closes" with it.

**Comment by MarijnS95** [comment]
Yes, we're figuring out why the wide angle camera lacks any video modes and hence crashes aosp cam at startup and opencam when starting a recording.

**Comment by Haxk20** [comment]
> Yes, we're figuring out why the wide angle camera lacks any video modes and hence crashes aosp cam at startup and opencam when starting a recording.

This is interesting. Because ganges has the same issue. But second camera reports video mode just fine to OpenCamera but still crashes AOSP camera.

**Comment by MarijnS95** [comment]
@Haxk20 Can you paste the exception thrown by AOSP camera?

When attempting to record a video on the wide angle camera on Seine, OpenCamera crashes as well.

**Comment by Haxk20** [comment]
> @Haxk20 Can you paste the exception thrown by AOSP camera?
> 
> When attempting to record a video on the wide angle camera on Seine, OpenCamera crashes as well.

Will do in chat when I get time.

**Comment by MarijnS95** [comment]
@Haxk20 Paste the exception here for posterity please :slightly_smiling_face:

**Comment by Haxk20** [comment]
[camera.mermaid.aosp.txt](https://github.com/sonyxperiadev/device-sony-pdx201/files/5304898/camera.mermaid.aosp.txt)
@MarijnS95

**Comment by Haxk20** [comment]
It seems like it cant find video stuff too even tho second camera reports it on open camera.

**Comment by Haxk20** [comment]
What happens tho is that open camera crashes when trying to record from camera ID 0
which is extremely weird.

**Comment by sjllls** [comment]
@MarijnS95  Might be useful.
On stock, 8MP sensors also take 12MP photos. IDK the reason. Might be related with
`Could not find supported video qualities.,SettingsUtil.java,347`

**Comment by sjllls** [comment]
#https://github.com/sonyxperiadev/device-sony-seine/pull/27

**Comment by MarijnS95** [comment]
@jerpelea iirc this still makes the front camera disappear from AOSP cam, that has to be investigated.

**Comment by Simonmicro** [comment]
> @jerpelea iirc this still makes the front camera disappear from AOSP cam, that has to be investigated.

Hmm, using LOS: Also no other camera works. No selfie, wide or zoom on the "Stock" camera app. There is a good chance that LOS uses an other camera app, so maybe I missed something else here :)

**Comment by MarijnS95** [comment]
@Simonmicro Still, it should allow using the front camera as before without sneakily "falling back" to the rear main shooter. Someone is still fighting with the IDs iirc, but no usable results as of yet.

**Comment by Haxk20** [comment]
Fighting with IDs sounds like me. I guess i know why switching them doesnt
work but no time as of yet yo look into it properly.

**Pull request merged**
